//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obuv_Prob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Article { get; set; }
        public System.DateTime Order_Date { get; set; }
        public Nullable<int> Adress_id { get; set; }
        public Nullable<int> Status_id { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public int Code { get; set; }
        public Nullable<int> User_Name { get; set; }
    
        public virtual Pu_Point Pu_Point { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual Users Users { get; set; }
    }
}
