//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obuv_Prob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Sopplier_id { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public Nullable<int> Category_id { get; set; }
        public int Discount { get; set; }
        public int Quantity { get; set; }
        public string Discription { get; set; }
        public string Photo { get; set; }
        public string Article { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufactures Manufactures { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
